---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - multicluster.x-k8s.io
  resources:
  - placementdecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.x-k8s.io
  resources:
  - placementdecisions/finalizers
  verbs:
  - update
- apiGroups:
  - multicluster.x-k8s.io
  resources:
  - placementdecisions/status
  verbs:
  - get
  - patch
  - update
