apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: placementdecision-consumer
  namespace: argocd
rules:
- apiGroups: ["multicluster.x-k8s.io"]
  resources: ["placementdecisions"]
  verbs: ["get", "list"]
