apiVersion: multicluster.x-k8s.io/v1alpha1
kind: PlacementDecision
metadata:
  labels:
    app.kubernetes.io/name: placement-api
    app.kubernetes.io/managed-by: kustomize
  name: placementdecision-sample
spec:
  # TODO(user): Add fields here
